apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
     name: ingr-calc
spec:
     rules:
     - host: www.k8scalc.net
       http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                   service:
                        name: serv-calc
                        port:
                             number: 4000
