apiVersion: apps/v1
kind: Deployment #Tipus de manifest
metadata:
     name: depl-llaunes #Nom del desplegament
spec: # Especificacions de desplegament
     replicas: 10 #Quantitat de Pods del desplegament
     selector: #El campo selector defineix com el Deployment identifica els Pods que ha de  gestionar
          matchLabels:
               # Part comuna i inical del nom intern dels Pods que formen part d'un desplegament
               # Qualsevol nom de pod que comenci amb aquest string forma part del desplegament
               # Aquest pods es poden generar amb aquest .yaml, altres .yaml i manualment
               app: llaunes-pods
     template: # Model de cadascun dels Pods creats i els contenidors amb l'aplicació
          metadata:
               labels:
                    # Part comuna i inicial del nom intern del Pods que es crearan amb aquest desplegament
                    # i a la qual s'afegirà un codi hash. Cada Pod comença amb aquest string.
                    # Per tant, aquest valor normalment coincidirà amb el valor app dins de selector->matcLabels->app.
                    app: llaunes-pods
          spec:
               containers:
               - name: llaunes-cont #Part inicial i comuna de tots els noms de contenidors creats dins d'un Pod
                 image: globproj2/llaunes:5.0 # Imatge amb la qual es crearan els contenidors. L'aplicació escolta en aquest pel port 80.
                 ports: # Port intern dins del contenidor pel qual escolta la nostra aplicació
                 - containerPort: 80
---
apiVersion: v1
kind: Service #Tipus de manifest
metadata:
     name: serv-llaunes  # nom identificador del servei
spec: # Especificacions del serveix
     type: NodePort # Es crea una IP pel servei que es pot enrutar cap els Pods. També indica que el valor "nodePort" s'utilitza per accedir a l'aplicació en els Pods des del host.  
     selector: # Indicacions per identificar els Pods amb els qual treballa el servei.
          app: llaunes-pods #Nom comú i inicial dels pods amb l'aplicació exposats pel servei. Ha de ser per tant igual a
                         # spec -> selector -> matchLabels -> app  del manifest del desplegament.
     ports:
     - port: 5000 # Port del servei accessible només internament pels Pods del deployment però no des del host. Aquest port enruta cap el port "targetPort" del Pod seleccionat  
       targetPort: 80 # Port dins dels Pod pel qual escolta l'aplicació. Hauria de ser per tant igual al valor containerPort del fitxer de desplegament.  
       nodePort: 31000 # Port del servei accessible des del host i a partir del qual es pot accedir a l'aplicació en els Pods.
                       # Aquest port s'enrutarà cap el port "targetPort" del Pod seleccionat 
