apiVersion: v1
kind: Service #Tipus de manifest
metadata:
     name: serv-calc  # nom identificador del servei
spec: # Especificacions del serveix
     type: NodePort # Es crea una IP pel servei que es pot enrutar cap els Pods. També indica que el valor "nodePort" s'utilitza per accedir a l'aplicació en els Pods des del host.  
     selector: # Indicacions per identificar els Pods amb els qual treballa el servei.
          app: calc-pods #Nom comú i inicial dels pods amb l'aplicació exposats pel servei. Ha de ser per tant igual a
                         # spec -> selector -> matchLabels -> app  del manifest del desplegament.
     ports:
     - port: 4000 # Port del servei accessible només internament pels Pods del deployment però no des del host. Aquest port enruta cap el port "targetPort" del Pod seleccionat  
       targetPort: 80 # Port dins dels Pod pel qual escolta l'aplicació. Hauria de ser per tant igual al valor containerPort del fitxer de desplegament.  
       nodePort: 30000 # Port del servei accessible des del host i a partir del qual es pot accedir a l'aplicació en els Pods.
                       # Aquest port s'enrutarà cap el port "targetPort" del Pod seleccionat 


